### Criar Usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "P4$sword",
  "confirmPassword": "P4$sword"
}

### Atualizar Usuário
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "email": "updated@example.com",
  "password": "NewP4$sword",
  "confirmPassword": "NewP4$sword"
}

### Anonimizar Usuário
DELETE http://localhost:3000/users/1
