## CREATE NEW USER
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "random@random.com",
  "password": "R@nd0mP@ssw0rd13"
}


### GET PROFILE
GET http://localhost:3000/users/
Accept: application/json
